### ISSUE TITLE
ASS 자막 변환 기능에 대해 질문드립니다

### ISSUE THREAD

**Issue by Noz0mizore** [harnenim/Jamaker#1]
![스크린샷 2024-12-05 204836](https://github.com/user-attachments/assets/a9fa54fa-4110-45c6-9723-eea65bb07385)

프로그램에 자세한 설명이 나오지 않아서 여러번 시도했는데

기본적인 텍스트 이외에 추가적인 태그가 붙은 SMI 파일은 변환이 불가한가요?

따로 태그 없는 구간만 시도할 시에는 정상적으로 변환이 가능한데 태그만 붙으면 변환이 불가능하더군요

그리고 변환기능에 설명을 보면 

이곳의 결과물은 완성본이 아니며, Aegisub에 복사한 후 추가 작업이 필요합니다.
화면 싱크를 사용한 경우 Default가 아닌 （］,［）,［］로 분류됩니다.

라고 적혀 있는데 변환한 뒤에 어떤 추가적인 작업이 필요할까요?

**Comment by harnenim** [comment]
아... 지금 한창 신규 기능 개발 중에 기존 코드가 오류 난 것 같네요...

**Comment by harnenim** [comment]
지금 ToAss.html 파일 수정해서 올렸고요.
지난주에 생성자 변경하면서 관련된 것들 같이 고치다가, 고칠 게 아닌데 비슷하게 생긴 걸 잘못 건드렸었네요...

그리고 추가적인 작업이란 건
기본적으로 smi에서 표현 가능한 간단한 태그 외에, ass에서만의 꾸미는 작업은 따로 해줘야 한단 의미입니다.

**Comment by Noz0mizore** [comment]
와... 빠른 대응 감사합니다 ruby태그나 폰트 컬러정도만 옮겨져도 충분할 거 같은데  그 영역은 가능한가요?

**Comment by Noz0mizore** [comment]
![스크린샷 2024-12-05 214026](https://github.com/user-attachments/assets/30935c31-3613-4d5c-b9a3-74d6379313b8)


수정된 ToAss.html 파일을 적용하니까 이제 태그 없는 대사도 변환이 안되네요?

혹시 제 환경이 문제일 가능성이 있을까요

**Comment by harnenim** [comment]
어... 뭔가 꼬이셨나 싶은데...
혹시 웹버전으로 해보셔도 그런가요?

**Comment by harnenim** [comment]
혹시 언제 받은 거에서 작업하고 계신가요?
한동안 안 건드리고 있다가 한 달쯤 전부터 되게 많이 뜯어고쳐서, 연관된 파일이 제대로 최신화가 안 됐으면 꼬일 것도 같거든요.

**Comment by Noz0mizore** [comment]
깃헙 링크에 있는 Jamaker_241121.zip 버전을 다운받아서 사용해보고 있습니다
그리고 웹버전 말인데요 샘플 페이지에서는 ASS변환 옵션이 안보이네요?

**Comment by harnenim** [comment]
웹샘플도 상단 메뉴는 C# 프로그램이랑 똑같이 보이게 했을 텐데...
일단 이걸로 덮어 씌우고 되시나 해보세요.
https://drive.google.com/file/d/1bTDyJI4YzxP6_vR1gCjDtkn4IuhNOizU/view

**Comment by harnenim** [comment]
참고로 왼쪽 아래 pos 태그 있는 부분은
요전에 ruby 태그 변환 추가했을 때 기본 위치 잡아주려고 넣은 부분입니다.

**Comment by Noz0mizore** [comment]
![스크린샷 2024-12-05 220953](https://github.com/user-attachments/assets/c3fa7374-dc1d-49b6-891c-da3f122b5e63)

웹샘플 파이어폭스로 테스트해보니까 화면 자체는 정상적으로 뜨는데 변환은 여전히 안되네요 브라우저 확장과 관련이 있을라나요

주신 파일 덮어씌우니까 자막 파일 읽어들이는거 자체에서 오류가 뜨네요

**Comment by harnenim** [comment]
이상하네요... 일단 저는 윈도우10이랑 맥북에서 작동이 확인이 되거든요...
크롬도 파폭도 돌아가고 있는데...

**Comment by harnenim** [comment]
일단 웹브라우저에서 돌아가는 건 F12 개발자도구도 보실 수 있을 거예요

**Comment by Noz0mizore** [comment]
![스크린샷 2024-12-05 223027](https://github.com/user-attachments/assets/c3a1149f-b578-4592-9058-62cf4f182b68)

변환 누르면 오류가 뜨는데 제가 못알아먹어서...

**Comment by harnenim** [comment]
아..... 혹시 카이란 님 자막인가요?
저거 문법상 color=F2EFD7 붙여 써야 맞는데, 팟플레이어에선 저렇게 써도 알아먹어서 저렇게 쓰시는 것 같던데...

**Comment by Noz0mizore** [comment]
아 자막 파일이 문제였구나... 괜히 시간 쓰게해서 죄송해요

**Comment by harnenim** [comment]
고민해 봤는데, 띄어쓰기가 들어간 경우도 해석이 돌아가도록 지원할 수 있으면 해보는 게 좋을 것 같네요.
일단 아예 오류가 나진 않게 고치는 게 좋겠고...

**Comment by harnenim** [comment]
지금 보니까 카이란 님이 ruby태그 안에서 [] 문자를 쓰시네요...
이 경우엔 ]가 오른쪽에 빠져버리는 문제가 발생하고 있습니다.
일단 주말에 신버전 올릴 것 같긴 한데...
